# Numpy  
* NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. 
* Using NumPy, mathematical and logical operations on arrays can be performed


In [1]:
import numpy as np
a=[1,2,3,4,5,3,6,7,8,8,9]   # Creating using numpy
np.array(a) # single dimensionalarray

array([1, 2, 3, 4, 5, 3, 6, 7, 8, 8, 9])

In [9]:
s=np.array([[1,2,3,4,5,],[6,7,8,9,10]]) # 2D array using matricies 
print(s.ndim)
print(s.shape)
print(s.size)
print(s.itemsize)
print(s.dtype)

2
(2, 5)
10
4
int32


In [4]:
data=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) # 3D array using matrices
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### ndim - displays the no of dimensions
### shape - returns the  no of rows and columns
### size - returns the no of elements
### itemsize -returns the no of bytes
### dtype - returns the datatype 

In [11]:
# shapes
# Tuple of array dimensions.
# The shape property is usually used to get the current shape of an array.
import numpy as np
data=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
#print(data)
data.shape
d=np.arange(0,101,10)
print(d)

[  0  10  20  30  40  50  60  70  80  90 100]


In [12]:
# arange
data=np.arange(0,100)# range of numbers
data=np.arange(0,100,2)#even numbers
data=np.arange(1,100,2)#odd Numbers
data=np.arange(100,0,-1)# numbers reverse
print(data)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]


In [13]:
n=np.arange(16).reshape(4,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
# random
s=np.random.randint(0,20,size=(2,5))
s

array([[ 0, 19, 18, 17,  8],
       [11,  5,  4,  6, 11]])

In [16]:
#Reshape: it returns the list of elements in the
#format of rows and columns.
import numpy as np
data=np.arange(0,100)
print(data)
data=data.reshape(10,10)
data


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
#Reshape: it returns the list of elements in the format of rows and columns.
import numpy as np
data=np.arange(0,50)
print(data)
data=data.reshape(5,10)
data


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [5]:
#Linspace: it returns a list at a specified range.
import numpy as np
data=np.linspace(0,1,10)
data


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [54]:
# Resize:  it working like as reshape()

import numpy as np
data=np.linspace(0,5,20)
#data
data.resize(4,5)
data

array([[0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158],
       [1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105],
       [2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053],
       [3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ]])

# Built in Functions
  ##### ones --> it will take upto 3  positional arguments(min 2)
  ##### zeros -->it will take upto 3  positional arguments(min 2)

In [18]:
import numpy as np
data=np.ones((3,3)) # by default it will return Float value
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
import numpy as np
data=np.ones((4,3),int)  # it will return integer value
data

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
import numpy as np
data=np.zeros((4,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# V-Stack: Stack arrays in sequence vertically (row wise).
n=np.ones([4,4],int)
n
np.vstack([n,8*n])


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [21]:
# H-Stack: Stack arrays in sequence horizontally (column wise).
import numpy as np
n=np.ones([5,6],int)
n
np.hstack([n,2*n])

array([[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]])

# operators


In [6]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([0,9,8,7,6])
n+n1

array([ 1, 11, 11, 11, 11])

In [7]:
import numpy as np
n=np.array([11,56,34,67,87])
n1=np.array([11,22,32,87,90])
n-n1

array([  0,  34,   2, -20,  -3])

In [22]:
import numpy as np
n=np.array([6,8,3,3])
n1=np.array([7,4,38,9])
print(n*n1)
n**n1

[ 42  32 114  27]


array([    279936,       4096, -400556711,      19683], dtype=int32)

In [3]:
import numpy as np 
k=input("enter values").split()
l=list(map(int,k))
m1=np.array(l)
print(m1)

enter values1 2 3 4 5
[1 2 3 4 5]


# BODMAS 
* Brackets of division
* Multiplication
* Addition
* Subtraction

In [112]:
# Dot: Return the dot product of two vectors.
import numpy as np
n=np.array([11,56,34,67,87])
n1=np.array([11,22,32,87,90])
n.dot(n1)

16100

In [117]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,n**2])
n1

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [118]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,pow(n,3)])
n1

array([[  1,   2,   3,   4,   5],
       [  1,   8,  27,  64, 125]])

# Transpose
* T ---> Attribute for Transpose
* transpose()

In [127]:
import numpy as np
n=np.array([[1,2,3,4,5],[0,9,8,7,6]])
n.T

array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6]])

In [128]:
import numpy as np
n=np.array([[1, 0],
           [2, 9],
           [3, 8],
           [4, 7],
           [5, 6]])
n.T

array([[1, 2, 3, 4, 5],
       [0, 9, 8, 7, 6]])

In [131]:
import numpy as np
n=np.array([[1,2,3,4],[4,5,6,7]])
n
n.transpose()

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

# Array datatype conversion:   
### Here we are discussing mainly two methods name as dtype() and astype().
*  by using dtype() we can find the list of  values belongs  to which type.
*  by using astype() we can perform the type conversions.


In [6]:
import numpy as np
n=np.array([1,3,5,7,9])
n.astype(str)
n.dtype

dtype('int32')

In [149]:
import numpy as np
n=np.array([1.5,3,5,7,9])
n
n.astype(int)
n.dtype

dtype('float64')

In [154]:
import numpy as np
n=np.array([1,2,3,4,5,6,7])
n
n.astype(int)
n.dtype

dtype('int32')

In [7]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
data
data.min()

0

In [160]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.min()

[[10  9  7]
 [ 7  5  2]
 [ 1  4 13]
 [12  4 11]]


1

In [161]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.max()

[[ 0  7  2]
 [ 0  7  9]
 [ 2 12 14]
 [ 3 10  1]]


14

In [162]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.mean()

[[ 9  1  8]
 [ 0  3  7]
 [10 14  8]
 [14 13  8]]


7.916666666666667

In [163]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.std()

[[ 5  9  1]
 [14  8  4]
 [ 3  6  4]
 [12 13 10]]


4.050891534245545

In [62]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.argmin()

[[ 7  5  2]
 [ 4  4  5]
 [ 5 13  4]
 [14 10  8]]


2

In [16]:
import numpy as np
d=np.array([1,7,98,5,6,3,98,7897])
d.argmax()


7

In [8]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.argmax()

[[ 2  1  3]
 [ 7  4  9]
 [ 4 11 12]
 [ 9  0 13]]


11

In [167]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.sum()

[[ 2  8  9]
 [10 10  1]
 [ 0 14 14]
 [ 9  2  5]]


84

# Iteraing over arrays

In [18]:
import numpy as np
s=np.random.randint(0,20,size=(4,3))
s

array([[16, 10,  6],
       [12,  5, 19],
       [19,  3, 17],
       [19, 10,  7]])

In [12]:
for row in s:
    print(row)

[19 15 17]
[ 0 11 18]
[18 12 19]
[12  9 10]


In [13]:
for row in range(len(s)):
    print(row)
    

0
1
2
3


In [15]:
for row,i in enumerate(s):
    print('row',row,'is',i)
    

row 0 is [19 15 17]
row 1 is [ 0 11 18]
row 2 is [18 12 19]
row 3 is [12  9 10]


# DataScience

. Business logics
