## NumPy Cont....

### BODMAS
    - Brackets of division
    - Multiplication
    - Addition
    - Subtraction

In [1]:
# Dot: Return the dot product of two vectors.
import numpy as np
n=np.array([11,56,34,67,87])
n1=np.array([11,22,32,87,90])
n.dot(n1)

16100

In [31]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,n**2])
n1

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [3]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,pow(n,3)])
n1

array([[  1,   2,   3,   4,   5],
       [  1,   8,  27,  64, 125]])

### Transpose

- T ---> Attribute for Transpose
- transpose()

In [33]:
n

array([[1, 2, 3, 4, 5],
       [0, 9, 8, 7, 6]])

In [32]:
import numpy as np
n=np.array([[1,2,3,4,5],[0,9,8,7,6]])
n.T

array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6]])

In [5]:
import numpy as np
n=np.array([[1, 0],
           [2, 9],
           [3, 8],
           [4, 7],
           [5, 6]])
n.T

array([[1, 2, 3, 4, 5],
       [0, 9, 8, 7, 6]])

In [6]:

import numpy as np
n=np.array([[1,2,3,4],[4,5,6,7]])
n
n.transpose()

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

### Array datatype conversion:

### Here we are discussing mainly two methods name as dtype() and astype().
- by using dtype() we can find the list of values belongs to which type.
- by using astype() we can perform the type conversions.

In [34]:
import numpy as np
n=np.array([1,3,5,7,9])
n.dtype

dtype('int32')

In [10]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
data
data.min()

0

In [11]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.min()

[[11  4  8]
 [ 0  1  0]
 [13  1  5]
 [12 12 13]]


0

In [36]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.max()

[[ 1 12  0]
 [11 10  9]
 [11  4  1]
 [ 3  1  0]]


12

In [13]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.mean()

[[12  4  0]
 [ 1 13  3]
 [14  9 13]
 [12  8  2]]


7.583333333333333

In [14]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.std()

[[10  5  9]
 [ 0 12  4]
 [ 0  6  2]
 [ 8  7  9]]


3.7416573867739413

In [18]:

import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.sum()

[[ 9  9  2]
 [ 4  8  8]
 [11  5 12]
 [13  9 14]]


104

In [37]:
np.log(0)

<ipython-input-37-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [38]:
np.log(1)

0.0

In [40]:
np.log(2)

0.6931471805599453

In [41]:
np.log([1,3,4,5])

array([0.        , 1.09861229, 1.38629436, 1.60943791])

In [42]:
np.sin(3)

0.1411200080598672

In [43]:
np.cos(4)

-0.6536436208636119

In [44]:
np.tan(5)

-3.380515006246586

In [45]:
np.sin([1,2,3])

array([0.84147098, 0.90929743, 0.14112001])

In [46]:
print(dir(np),end=' ')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

## Pandas
- Means PanelData
- One of the data science packages
- Used for data manupulation,analysis and cleaning
- Contains mainly two data strucutes
    - 1.Series
    - 2.DataFrames
- A series is a sequence of data
- A data frame is a data with rows and columns


In [47]:
import pandas as pd


In [48]:
pd.__version__

'1.0.5'

## Series

In [49]:
s = 'data'
pd.Series(s)

0    data
dtype: object

In [50]:
s1 = 'hi hello welcome'.split()
pd.Series(s1)

0         hi
1      hello
2    welcome
dtype: object

In [51]:
s1 = 'hi hello welcome'.split()
pd.Series(s1,index = ['str1','str2','str3'])

str1         hi
str2      hello
str3    welcome
dtype: object

In [53]:
li = [123,'abc',5.78]
pd.Series(li,index = ('int','str','float'))

int       123
str       abc
float    5.78
dtype: object

In [ ]:
123 -- abc
456 -- tyu


In [54]:
t = ('ramu','raju','nandini')
pd.Series(t, index = ['123','124','125'])

123       ramu
124       raju
125    nandini
dtype: object

In [57]:
dic = {'key1':123,'key2':'hello','key3':5.3}
pd.Series(dic)

key1      123
key2    hello
key3      5.3
dtype: object

In [58]:
import numpy as np

In [59]:
ar = np.arange(1,10)

In [60]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
pd.Series(ar)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

## DataFrames

In [63]:
st = 'welcome to today session'.split()
pd.DataFrame(st)

0
0  welcome
1       to
2    today
3  session

In [64]:
st = 'welcome to today session'.split()
pd.DataFrame(st, index = [1,2,3,4]) 

0
1  welcome
2       to
3    today
4  session

In [65]:
li = ['a','e','i','o','u']
pd.DataFrame(li, index = ('v1','v2','v3','v4','v5'))


0
v1  a
v2  e
v3  i
v4  o
v5  u

In [67]:
d = {'k1':'hi','k2':'hello','k3':'welcome'}
pd.DataFrame(d,index = [1,2,3])

k1     k2       k3
1  hi  hello  welcome
2  hi  hello  welcome
3  hi  hello  welcome

In [68]:
d2 = {'Names':['First_name','Second_name','Third_name'],'Marks':[20,30,50],
      'Id':['N130663','N130664','N130665']}
pd.DataFrame(d2,index=['Stu1','Stu2','Stu3'])

Names  Marks       Id
Stu1   First_name     20  N130663
Stu2  Second_name     30  N130664
Stu3   Third_name     50  N130665

### Slicing

In [69]:
import numpy as np
s = pd.Series(np.random.randint(20,40,8))
s

0    27
1    24
2    26
3    37
4    36
5    29
6    22
7    39
dtype: int32

In [74]:
print(s[1])
print(s[1:5])
print(s[:6])
print(s[::])
print(s[1:7:2])

24
1    24
2    26
3    37
4    36
dtype: int32
0    27
1    24
2    26
3    37
4    36
5    29
dtype: int32
0    27
1    24
2    26
3    37
4    36
5    29
6    22
7    39
dtype: int32
1    24
3    37
5    29
dtype: int32


## Data Analysis and Manupulation

In [75]:
df1 = pd.DataFrame({'mv_rating':[4,5,6,3],'no_of_persons':[50,45,35,67]},
                  index=[2000,2020,2030,2045])
df1

mv_rating  no_of_persons
2000          4             50
2020          5             45
2030          6             35
2045          3             67

In [76]:
df2 = pd.DataFrame({'no_of_heros':[1,3,2,4],'no_days':[122,345,67,8]},
                  index = [2000,2032,2045,2345])
df2

no_of_heros  no_days
2000            1      122
2032            3      345
2045            2       67
2345            4        8

In [77]:
df1.join(df2)

mv_rating  no_of_persons  no_of_heros  no_days
2000          4             50          1.0    122.0
2020          5             45          NaN      NaN
2030          6             35          NaN      NaN
2045          3             67          2.0     67.0

In [78]:
df2.join(df1)

no_of_heros  no_days  mv_rating  no_of_persons
2000            1      122        4.0           50.0
2032            3      345        NaN            NaN
2045            2       67        3.0           67.0
2345            4        8        NaN            NaN

In [80]:
df3 = pd.DataFrame({'a':[80,90,60,70],
                   'b':[2,1,2,3],
                   'c':[50,45,45,67]},
                  index = [2001,2002,2003,2004])
df3

a  b   c
2001  80  2  50
2002  90  1  45
2003  60  2  45
2004  70  3  67

In [81]:
df4 = pd.DataFrame({'a':[80,69,60,70],
                   'b':[2,1,2,3],
                   'c':[50,45,45,67]},
                  index = [2001,2002,2003,2004])
df4

a  b   c
2001  80  2  50
2002  69  1  45
2003  60  2  45
2004  70  3  67

In [82]:
df3.merge(df4)

a  b   c
0  80  2  50
1  60  2  45
2  70  3  67

In [83]:
concatination = pd.concat([df1,df2])
concatination

mv_rating  no_of_persons  no_of_heros  no_days
2000        4.0           50.0          NaN      NaN
2020        5.0           45.0          NaN      NaN
2030        6.0           35.0          NaN      NaN
2045        3.0           67.0          NaN      NaN
2000        NaN            NaN          1.0    122.0
2032        NaN            NaN          3.0    345.0
2045        NaN            NaN          2.0     67.0
2345        NaN            NaN          4.0      8.0

In [84]:
dates = pd.date_range('2020-10-01','2020-10-20')
dates

DatetimeIndex(['2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04',
               '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
               '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12',
               '2020-10-13', '2020-10-14', '2020-10-15', '2020-10-16',
               '2020-10-17', '2020-10-18', '2020-10-19', '2020-10-20'],
              dtype='datetime64[ns]', freq='D')